### ISSUE TITLE
Comentarios QMP1

### ISSUE THREAD

**Issue by ggallici** [Rodri-Putrino/QueMePongo#1]
Buenas, como va? Antes que nada, perdón por la demora para el feedback.
Te voy marcando algunas cositas que fui viendo:

- Cuidado con confundir a los actores del sistema (`Usuario`) con objetos del sistema y los casos de uso (`cargarPrenda`) con los mensajes que entienden esos objetos. El requerimiento nos pedía poder construir prendas válidas, no almacenarlas. 
- De la misma forma que`Material`, el tipo de la prenda y la categoría tienen pinta de tener un conjunto acotado de valores posibles, lo cual matchea bien con utilizar `enums` (y que tiene todas las ventajas que ya vimos en clase).
- Aunque como ya te expliqué más arriba, los mensajes `cargarPrenda` son incorrectos ya que modelan casos de uso, fijate que además tienen lógica repetida que podría ser extraída en un mensaje que reciba la prenda, haga la validación y la agregué a la lista.
- Si bien usar `enums` para modelar los colores es un solución superadora a utilizar `strings`, puede llevar a una clasificación un poco arbitraria (ROSA, ROSA_CLARITO, ROSA_MUY_CLARITO, etc) y, además, nos acota demasiado los posibles valores de colores del sistema. Una buena alternativa sería modelar los colores como una combinación RGB que es un poco mas standard y nos da un plus de flexibilidad.
- Si bien la idea que tuviste para validar que los tipos/categorías se condigan es correcta (se podría mejorar haciendo a ambos `enums`), existe otra forma que nos evita tener que hacer ésta validación **impidiendo** que se carguen tipos con categorías incorrectas:
```java
public enum TipoPrenda {
  ZAPATOS(CategoriaPrenda.CALZADO),
  CAMISA(CategoriaPrenda.PARTE_SUPERIOR),
  ...

  ;

  private CategoriaPrenda categoria;

  TipoPrenda(CategoriaPrenda categoria) {
    this.categoria = categoria;
  }
}

//De esta forma los tipos tienen sus categorías correspondientes y no debemos preocuparnos por validarlos
```

Igualmente, tu solución está muy muy bien 🥳.
Saludos y nos vemos el Viernes!

**Comment by Rodri-Putrino** [comment]
Hola! Muchas gracias por las correcciones, las tendré en cuenta!
Nos vemos el viernes!
